name:                data-named
version:             0.6.2
github:              "kawu/data-named"
license:             BSD3
author:              "Jakub Waszczuk"
maintainer:          "waszczuk.kuba@gmail.com"
copyright:           "2012-2019 IPI PAN, Jakub Waszczuk"

extra-source-files:
- README.md
# - ChangeLog.md

# Metadata used when publishing your package
synopsis:            Data types for named entities
category:            Natural Language Processing

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kawu/data-named#readme>

dependencies:
- base                >= 4.8      && < 5
- containers          >= 0.5      && < 0.7
- text                >= 1.1      && < 1.3
- attoparsec          >= 0.12     && < 0.14
- binary              >= 0.7      && < 0.9

library:
  source-dirs: src
